server.port: 18080

spring:
  application:
    name: todo-server
  datasource:
    url: jdbc:h2:file:~/.h2/kindless/todo
    username: sa
    password: null
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
